//Program soal quiz menggunakan perulangan (while-do while-for)
#include<stdio.h>
#include<conio.h>
#include<string.h>

main()
{
 char nmr[100][5],nps[100][10],kls[100],png[100][6];
 int lmi[100];
 }
 Rklinik;
 int i,jdp,brs;
 float bpi,bpl,byi,byl,byb,tby,tbyk;
 char ul,map;

 ul='y';
 while(ul=='y')
 {
  i=1;
  do
  {
   clrscr();
   puts("Klinik Bersalin Sehat & Sejahtera");
   puts("     Entry Data Persalinan       ");
   puts("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
   printf("Data Persalinan Ke. &i\n",i);
   printf("Nomor MR     : ");scanf("&s",Rklinik.nmr[i]);fflush(stdin);
   printf("Nama Pasien  : ");scanf("%s",Rklinik.nps[i]);fflush(stdin);
   printf("Kelas        : ");scanf("%s",Rklinik.kls[i]);
   printf("Penginapan   : ");scanf("%s",
