//Program Jawaban Soal UTS
#include<stdio.h>
#include<conio.h>
#include<string.h>
main()
{
 struct
 {
  char ids[100][5],nms[100][10],kd[100][2];
  float jls[100];
  }Rangkuman
  char jna[8],als,tds;
  int i,brs,jds;
  float swj,ups,klb,phs,php,tphs,tphp,bns,bnp;
  als='y';
  i=1;
  while(als=='y')
  {
   do
    {
    clrscr();
    puts("Usaha Angkutan Kota");
    puts(" Entry Data Setoran ");
    puts("~~~~~~~~~~~~~~~~~~~~");fflush(stdin);
    printf("Data Setoran Ke.%i\n",i);
    printf("ID Sopiir	  : ");gets(Rangkutan.ids[i]);
    printf("Nama Sopir    : ");gets(Rangkutan.nms[i]);
    printf("Kode(MI/MB/IX : ");gets(Rangkutan.kd[i]);
    printf("Jumlah Setoran: ");scanf("%f",&Rangkutan.jls[i]);
    gotoxy(1,10);printf("Jumlah Data Setoran ? Y/T[.]");
    gotoxy(27,10);tds=getche();
    jds=i;
    i++

